### PR TITLE
⚡️ Update request content type to form

### PR DESCRIPTION
**Pull request by Nikosmonaut**
Body params should be url encoded to be send as x-www-form-urlencoded
Standardize ID case for params (It's a breaking change)

### Description:
-

### CODE REVIEW

**Comment by A-Tokyo** [comment]
Hey @Nikosmonaut, Nice work!!

- why do we need to we need to switch `teamId` to `teamID`? This is a breaking change that i think is not needed. Since the library works perfectly with `teamId`.
- Can you clarify why you switched the form from json to url form encoded? Again it's working afik

Thanks again!

NOTE: I enabled the CI for PRs now, so please push any comment to trigger a rebuild

**Comment by Nikosmonaut** [comment]
> why do we need to we need to switch teamId to teamID? This is a breaking change that i think is not needed. Since the library works perfectly with teamId.

Yes it is. It was a proposal. But it seems kind of wrong to me when 2 differents notations coexist. It is up to you to decide of course. I can revert it
```
    clientID: string,
    teamId: string,
```

> Can you clarify why you switched the form from json to url form encoded? Again it's working afik

Because it does not work. At least for me. I did non have it tested by other people. That's why I created an issue to ask if someone had success sending post params by stringifying json data.

```
  return fetch(url.toString(), {
    method: 'POST',
    body: JSON.stringify(form),
```

Following this feed people struggle with the same issue and the solution was to send data url encoded with x-www-form-urlencoded content-type. [apple forum](https://developer.apple.com/forums/thread/124521)

Of course if it works for you, don't take into account this PR, and I wil import this code into my project.

**Comment by A-Tokyo** [comment]
@Nikosmonaut Makes sense.

How about we split this PR into two PRs. We merge the form bugfix as a minor change and later merge the variable renaming breaking change with the next major release?

Can you confirm that the form change allows you to fully handle apple authentication in your app? - I will double check the changes on my end as well

**Comment by A-Tokyo** [comment]
@Nikosmonaut Hey! Sorry for the delay

Thanks for the PR!

Please increment the minor version number `0.X.0` and I will release once ready. Also please ensure it's working in your app 💪

**Comment by Nikosmonaut** [comment]
@A-Tokyo just to remind. I updated my PR )

**Comment by A-Tokyo** [comment]
Done 👍  @Nikosmonaut

**Pull request merged**
