### PR TITLE
✨ Custom fetch - Proxy support

### PR DESCRIPTION
**Pull request by NitinHsharma**
Added support for proxy with additional function **_setFetch**

### CODE REVIEW

**Comment by A-Tokyo** [comment]
Awesome job @NitinHsharma !!

Can we please update the docs as well?

Maybe add this section above `## Extras`? 🤔 
```md
### Extra API functions
- _setFetch: `(fetchFn: function) => void` - Sets the fetch function, defaults to node-fetch. eg: appleSigninAuth._setFetch(fetchWithProxy);
```

**Comment by A-Tokyo** [comment]
Also can you please bump the minor version number from 0 to 1? 🚀

**Comment by NitinHsharma** [comment]
Documentation and minor version updated

**Comment by A-Tokyo** [comment]
@NitinHsharma Ohh shoot I didn't notice that we forgot to reset the patch version number to zero. So i release a new version 1.2.0 ( : to maintain proper versioning. 1.1.13 is now rendered obsolete since it's semantically incorrect

**Pull request merged**
